export const SET_ALERT ='SET_ALERT';
export const REMOVE_ALERT ='REMOVE_ALERT';
export const REGISTER_SUCCESS ='REGISTER_SUCCESS';
export const REGISTER_FAIL ='REGISTER_FAIL';
export const USER_LOADED ='USER_LOADED';
export const AUTH_ERROR ='AUTH_ERROR';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAIL ='LOGIN_FAIL';
export const LOGOUT ='LOGOUT';
export const GET_PROFILE ='GET_PROFILE';
export const PROFILE_ERROR ='PROFILE_ERROR';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const TEACHERS_LOADED = 'TEACHERS_LOADED';
export const TEACHER_PROFILE_SELECTED = 'TEACHER_PROFILE_SELECTED';
export const RESERVATION_SUCCESS = 'RESERVATION_SUCCESS';
export const BLOGS_LOADED = 'BLOGS_LOADED';
export const BLOG_SELECTED = 'BLOG_SELECTED';
export const BLOG_POSTED = 'BLOG_POSTED';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const NOTIFICATION_REMOVED = 'NOTIFICATION_REMOVED';
export const COMMENTS_LOADED = 'COMMENTS_LOADED';
export const COMMENT_ADDED = 'COMMENT_ADDED';
export const COMMENT_FAILED = 'COMMENT_FAILED';






